services:
  db:
    image: ghcr.io/dbsystel/postgresql-partman
    environment:
      POSTGRES_USER: "yu"
      POSTGRES_PASSWORD: "yu"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
  reddit_snap:
    env_file: ".env"
    build: 
      context: ./SnapReddit_dev
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  reddit_snap_front:
    env_file: ".env"
    build:
      context: ./reddit-snap-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy